version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chattingo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_DATABASE: chattingo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chattingo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chattingo-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chattingo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chattingo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chattingo-network

volumes:
  mysql_data:

networks:
  chattingo-network:
    driver: bridge